# Generated by Django 5.2.6 on 2025-10-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=355),
        ),
    ]
